{% set name = "ovito" %}
{% set version = "3.3.1" %}
{% set sha256 = "b0bd9a3d5bf2c3fd709985437f8ae10ad0567ffcc71255a0d4a73748f2c7858c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/stuko/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libXau') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - cmake
    - make
  host:
    - boost
    - ffmpeg
    - libnetcdf
    - qt
    - zlib
  run:
    # nettle from defaults is not compatible
    - {{ pin_compatible('nettle', exact=True) }}

test:
  commands:
    - command -v ovito

about:
  home: https://www.ovito.org
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Scientific visualization and analysis software for atomistic simulation data'
  description: |
    OVITO is a scientific visualization and analysis software for
    atomistic and particle simulation data. It helps scientists gain
    better insights into materials phenomena and physical processes.
    OVITO is being developed by Alexander Stukowski at Darmstadt
    University of Technology, Germany.
  doc_url: http://www.ovito.org/
  dev_url: https://gitlab.com/stuko/ovito

extra:
  recipe-maintainers:
    - jan-janssen
