travis:
  secure:
    BINSTAR_TOKEN: huBPNSfb3JACdW8aIzSY+GcUF9fE9gX+IsAYuO3tPirq3xfmCUVwPtQExo5tCPTWBs3W2Be+dmeKiL0pTZbc26wlG9BKzQic0u/OdfCH0fgdCaJopJf7tuzFU7qyOMTWkZ2bJyHWv1uTj3KIo9MfLWaYCeRk3yLzhPlVPPfMPskFDzAKQc0laBZty2b5mPv17hkZEX9ubxfy/fZ/j0YFLscaKPKM0jQvG0k1Suj5Z1zf+N3/+llJvSUQAWYYF+zEfWqV8IpbXHSMZuypbzpndeunI+c8bi5epb3tGNYFIizdE4GSp3KXGXKvM+cCCTky7yg7ZTtJNLyhRg7kChL0ZVkT2YZmehJ2KRVjklgpm4j4x4bFbTNM7vkCYelQIJZNQyh9lWFL2q/a7hFD0x5qDihr/cH1PnxQ2jGWOD1b51hnpItAFFHgd/YMnKMOctZVYw6Z7jbEhfUdS1XzVgOCqIWEwyxeySlVlc/+y6a1qN7d/N3IBuqFAZpE19tdgFSXu+FxjWhaHAex4m/XwAGQn2IiQ5DFO6ebESBrB0TcgPSTfmJsxx3YGduf9i/rlRhCtrIXfWXmN92DTkpvbyrwiviDjbSRF8vNhIOH4xJTm/s1h6a1hwl+TYCfc1qJhMuE0HRcV71kvaa7p+K0RnGPA1D1IroGQgnrp+9IOheZeSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
