travis:
  secure:
    BINSTAR_TOKEN: DBW6JH2rwaGvLRePGTrI365rjLYR3hYbHR6yEbBHfpClUS0Y1QQPIGzTtHc5Wu6DGt2b4FfHoIouYnEPq7UWXK8OeEkiexIbbVUwYTbnwPyq8hQwWWRB80WYOUGu9d5PB9P5v+eVLDK2rPtkQZusAtyxRpO+vRbCVvHjyV402RaHbByf+n1WKPLMKX6T5c04FCKo49g6Nq/8rUwdGQak8A3NJCzCDYKoAF8IH5Zn1AygzZeDeI+xmoI8TeKGsJAsfXLV21IaHyn/4+vyi6L6vb7MN2ZsmwEg8U6NrGSlBnP5xl7PCs7Sphdw5FEYIJYwkQk8bRxM9ChTEi+z3ikgfNbRSyDgHlu9c4MqMx4Jpu57UYQqqqCXYg+GdMNnn1kUZ7EO6FKBa5PNEm0CnZ+nVnhM5PsJrwF/cNnAsov7QAiv0zbPHOonU0bzST2jgZOS6ARbPdgaul+1/w/IjWd17zVCSn3nV3AhNs1SaiUjuyeVqN20o8RNvKywaqHfN1ATtBc0+RThOq6epcQn1cBtJFS6clie+ijQOOTIcvBGNDHc1D9zH6IhMtYY/xXCGR5TxA54tIIs52XjCvUHQR5ENQWsDnrDnz2AIeFFn3UIXtHDlrYSb4eyOKycuw5A2eoDRcMCuD4QPRdZY7ePNXFUgOxyL82O6E2FHwy7oTHna78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
